#!/bin/sh
# Docker-only: starts the app on :8000; optionally enables HTTPS (Caddy on :443) when ENABLE_HTTPS=1.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT" || exit 1

. "$SCRIPT_DIR/dotenv.sh"
dotenv_load "$ROOT/.env"

# Truthy env helper (1/true/yes/on).
is_truthy() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|y|on) return 0 ;;
    *) return 1 ;;
  esac
}

# Do not name this "dc" — that shadows /usr/bin/dc (desk calculator) with `exec`.
run_compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

compose_run() {
  (cd "$ROOT/docker" && run_compose "$@")
}

if ! is_truthy "${ENABLE_HTTPS:-0}"; then
  echo "Starting app (HTTP-only) — http://127.0.0.1:8000/" >&2
  compose_run up --build checkout-sample
  exit 0
fi

"$SCRIPT_DIR/setup-hosts.sh"
"$SCRIPT_DIR/ensure-certs.sh"

HOST="${HOST:-www.test.com,test.com}"
_host_list=$(printf '%s' "$HOST" | tr ',' ' ' | tr -s '[:space:]' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
if [ -z "$_host_list" ]; then
  echo "HOST is empty in .env" >&2
  exit 1
fi
_caddy_addrs=$(printf '%s' "$_host_list" | awk '{gsub(/ /, ", "); print}')
AUTO="$ROOT/docker/Caddyfile.docker.auto"
{
  printf '%s\n' '# Generated by ./scripts/start.sh for Docker Caddy'
  printf '%s\n' "$_caddy_addrs {"
  printf '\ttls /etc/caddy/cert.pem /etc/caddy/key.pem\n'
  printf '\treverse_proxy checkout-sample:8000\n'
  printf '%s\n' "}"
} >"$AUTO"
echo "Wrote $AUTO (HOST=$HOST)" >&2

echo "Starting app + Caddy — https://$(printf '%s' "$_host_list" | awk '{print $1}')/ (and :8000)" >&2
compose_run up --build
